safe:        false
port: 5000
baseurl:    /
# url: http://ckreutz.github.io/crisscrossed-blog
url: http://localhost:3000
production: false

exclude: ["node_modules", "gulpfile.js", "package.json"]

source:      .
destination: ./_site

future:      true
lsi:         false
permalink:   /:year/:month/:day/:title.html
markdown:    rdiscount

sass:
  style: :compressed
