safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000

source:      .
destination: ./_site

future:      true
lsi:         false
pygments:    false
permalink:   /:year/:month/:day/:title
markdown:    rdiscount

rdiscount:
  extensions: []

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  
mini_magick:
  thumbnail:
    source: images/photos/original
    destination: images/photos/thumbnail
    resize: "100x100"
  medium:
    source: images/photos/original
    destination: images/photos/medium
    resize: "600x400"
