safe:        false
port: 5000
baseurl:    /
url: http://localhost:4000
production: false

source:      .
destination: ./_site

future:      true
lsi:         false
permalink:   /:year/:month/:day/:title
markdown:    rdiscount

sass:
  style: :compressed

# mini_magick:
#   small:
#     source: images/_photos/original
#     destination: images/photos/small
#     #gravity: center
#     #resize: "150x150"
#   ttest:
#     source: images/_photos/original
#     destination: images/photos/ttest
#     #gravity: center
#     #resize: "360x350"
#   medium:
#     source: images/_photos/original
#     destination: images/photos/medium
#     resize_to_fit: "595x280"
