safe:        false
port: 5000
baseurl:    /
url: http://localhost:4000
production: false

source:      .
destination: ./_site

future:      true
lsi:         false
permalink:   /:year/:month/:day/:title
markdown:    rdiscount

sass:
  style: :compressed

mini_magick:
  small:
    source: images/_photos/original
    destination: images/photos/small
    gravity: center
    extent: "150x150"
    resize: "150x150"
  thumbnail:
    source: images/_photos/original
    destination: images/photos/thumbnail
    gravity: center
    extent: "360x300"
    resize: "360x200"
  medium:
    source: images/_photos/original
    destination: images/photos/medium
    gravity: center
    extent: "670x280"
    resize: "670x280"
