safe:        false
port: 4000
baseurl:    /
url: http://localhost:4000

source:      .
destination: ./_site

future:      true
lsi:         false
highlighter:    false
permalink:   /:year/:month/:day/:title
markdown:    rdiscount

rdiscount:
  extensions: []

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

mini_magick:
  small:
    source: images/_photos/original
    destination: images/photos/small
    gravity: center
    extent: "150x150"
    resize: "150x150"
  thumbnail:
    source: images/_photos/original
    destination: images/photos/thumbnail
    gravity: center
    extent: "360x300"
    resize: "360x200"
  medium:
    source: images/_photos/original
    destination: images/photos/medium
    gravity: center
    extent: "670x280"
    resize: "670x280"
