safe:        false
port: 5000
baseurl:    /
#url: http://ckreutz.github.io/crisscrossed-blog
production: false

exclude: ["node_modules", "gulpfile.js", "package.json"]

source:      .
destination: ./_site

future:      true
lsi:         false
permalink:   /:year/:month/:day/:title.html
markdown:    rdiscount

navigation:
  - text: Blog
    url:
    name: blog
  - text: About
    url: about
    name: about
  - text: Archive
    url: archive
    name: archive
  - text: Deutsch
    url: de
    name: de
