safe:        false
port: 5000
baseurl:    /
url: http://ckreutz.github.io/crisscrossed-blog
# url: http://localhost:5000
production: false

source:      .
destination: ./_site

future:      true
lsi:         false
permalink:   /:year/:month/:day/:title
markdown:    rdiscount

sass:
  style: :compressed
